name: Dependency Scan

on: 
    workflow_call:
      
jobs:
  
    Dependency-Scan:
        
        runs-on: ubuntu-latest

        steps:

          - name: checkout
            uses: actions/checkout@v4