name: Deploy Porfolio

on:
    workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
        
      - name: checkout
        uses: actions/checkout@v5

      - name: Deploy with docker compose
        run: docker compose up -d --build