name: Docker Build & push

on:
    push:
        branches:
          - main


jobs:

    Build:

        runs-on: ubuntu-latest

        steps:
          - name: code checkout
            uses: actions/checkout@v4

          - name: login to docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ vars.USER }}\
                password: ${{ secrets.TOKEN }}

          - name: Build and Push to Docker Hub
            uses: docker/build-push-action@v6
            with:
                push: true
                tags: |
                    ${{ vars.User }}/github-actions-app:${{ github.ref_name }}
                    ${{ vars.User }}/github-actions-app:latest
                    ${{ vars.User }}/github-actions-app:${{ github.sha }}
  
